### PR TITLE
Updates for new versions of logstash support

### PR DESCRIPTION
**Pull request by mjnorman**
This is just a bit premature, but wanted to just get this out there.  This compiles, installs to logstash and runs, but I do get a null reference, at the below stack trace.  On the way to fixing #1 .  Please provide feedback, looking to learn more Ruby so any tips or pointers you can give would be great.  Thanks!

```{:error=>#<NoMethodError: undefined method `each' for nil:NilClass>, :backtrace=>["C:/logstash-6.4.1/vendor/local_gems/04b715e6/logstash-output-seq-0.0.4/lib/logstash/outputs/seq.rb:122:in `to_seq_payload'", "C:/logstash-6.4.1/vendor/local_gems/04b715e6/logstash-output-seq-0.0.4/lib/logstash/outputs/seq.rb:51:in `block in multi_receive'"```

-Update dependencies
-Update event['field'] references event.get('field')
-Update gitignore
-Update version to 0.0.4

Thanks for contributing to the Seq output plugin for Logstash!

### CODE REVIEW

**Review by tintoy — COMMENTED** [review]
Thanks for getting involved! Will look at this once I've had some sleep :)

**Comment by mjnorman** [comment]
No problem. This is just a learning experience for me now so don’t feel obligated to this PR :)

**Comment by tintoy** [comment]
I'm a Ruby noob, too, so I guess we'll both be learning :)

**Comment by tintoy** [comment]
Hey - I've created a new PR incorporating your changes as well as a couple of other changes required for compatibility with newer Logstash versions (also, added you to the CONTRIBUTORS file since you deserve the credit for most of these changes) so I'm going to close this one :)

**Pull request closed without merging**
